apiVersion: v1
kind: Service
metadata:
  name: namespace-aplicacionGeneral-nombremicrofrontend-service-prod
  namespace: namespace-aplicacionGeneral-nombremicrofrontend-prod
spec:
  selector:
    app: namespace-aplicacionGeneral-nombremicrofrontend-prod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31111
  type: NodePort