apiVersion: v1
kind: Service
metadata:
  name: namespace-aplicacionGeneral-nombremicrofrontend-service-dev
  namespace: namespace-aplicacionGeneral-nombremicrofrontend-dev
spec:
  selector:
    app: namespace-aplicacionGeneral-nombremicrofrontend-dev
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32222
  type: NodePort